Document: sctpscan
Title: Debian sctpscan Manual
Author: <insert document author here>
Abstract: This manual describes what sctpscan is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sctpscan/sctpscan.sgml.gz

Format: postscript
Files: /usr/share/doc/sctpscan/sctpscan.ps.gz

Format: text
Files: /usr/share/doc/sctpscan/sctpscan.text.gz

Format: HTML
Index: /usr/share/doc/sctpscan/html/index.html
Files: /usr/share/doc/sctpscan/html/*.html
